server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/hotel-service

  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: false
      register-with-eureka: true
      service-url:
        default-zone: http://localhost:8761/eureka
